-- Databricks notebook source
-- MAGIC %python
-- MAGIC REGISTER = spark.sql(f'''
-- MAGIC     SELECT DISTINCT
-- MAGIC     ef_fund_id FUND_ID
-- MAGIC     , ef_fund FUND
-- MAGIC     , ef_portfolio_id PORTFOLIO_ID
-- MAGIC     , ef_portfolio PORTFOLIO
-- MAGIC     FROM oegen_data_prod_prod.efront.silver_aum_metrics_enriched
-- MAGIC ''')
-- MAGIC
-- MAGIC REGISTER.createOrReplaceTempView("REGISTER")

-- COMMAND ----------

-- DBTITLE 1,AUM BRIDGE BASE
-- MAGIC %python
-- MAGIC AUM_BRIDGE_BASE = spark.sql(f'''
-- MAGIC WITH RAW as (
-- MAGIC     SELECT 
-- MAGIC         ef_fund_id FUND_ID
-- MAGIC         , ef_fund FUND
-- MAGIC         , ef_portfolio_id PORTFOLIO_ID
-- MAGIC         , ef_portfolio PORTFOLIO
-- MAGIC         , REPORT_DATE
-- MAGIC         , COALESCE(AUM, 0) AS AUM
-- MAGIC         , COALESCE(ASSET_DEBT_CMT, 0) + COALESCE(ASSET_EQUITY_CMT, 0) + COALESCE(ADJ_UNDRAWNCOMMITMENT, 0) AS ASSET_COMMITTED_EQUITY
-- MAGIC         , COALESCE(ASSET_DEBT, 0) AS ASSET_EXTERNAL_DEBT
-- MAGIC         , COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) + COALESCE(FUND_REMOVE_DBL, 0) AS FUND_LEVEL_ADJ
-- MAGIC     FROM oegen_data_prod_prod.efront.silver_aum_metrics_enriched
-- MAGIC )
-- MAGIC , AUM AS (
-- MAGIC     SELECT 
-- MAGIC     FUND_ID
-- MAGIC     , FUND
-- MAGIC     , PORTFOLIO_ID
-- MAGIC     , PORTFOLIO
-- MAGIC     , REPORT_DATE
-- MAGIC     , SUM(ASSET_COMMITTED_EQUITY) AS ASSET_COMMITTED_EQUITY
-- MAGIC     , SUM(ASSET_EXTERNAL_DEBT) AS ASSET_EXTERNAL_DEBT
-- MAGIC     , SUM(FUND_LEVEL_ADJ) AS FUND_LEVEL_ADJ
-- MAGIC     , SUM(AUM) CLOSING_AUM
-- MAGIC     FROM RAW
-- MAGIC     GROUP BY ALL
-- MAGIC     ORDER BY REPORT_DATE
-- MAGIC )
-- MAGIC , TX AS (
-- MAGIC   SELECT 
-- MAGIC     ef_fund_id FUND_ID
-- MAGIC     , ef_fund FUND
-- MAGIC     , ef_portfolio_id PORTFOLIO_ID
-- MAGIC     , ef_portfolio PORTFOLIO
-- MAGIC     , tx_effective_report_date AS REPORT_DATE
-- MAGIC     , CASE WHEN type IN ("EQ - Purchase/Subscription (w/o Commitment)",
-- MAGIC       "EQ - Subscription (Capital Issue following Commitment)",
-- MAGIC       "LN - Advance/Purchase (w/o commitment)",
-- MAGIC       "LN - Advance (following Commitment)") THEN -amount_gbp
-- MAGIC       ELSE 0
-- MAGIC       END AS CAPITAL_INJ
-- MAGIC     , CASE WHEN type = "EQ - Sale/Redemption" THEN -amount_gbp
-- MAGIC       ELSE 0
-- MAGIC       END AS DISPOSAL
-- MAGIC     FROM oegen_data_prod_prod.efront.silver_aum_capital_injections_and_disposals_transactions
-- MAGIC )
-- MAGIC , TRX AS (
-- MAGIC     SELECT 
-- MAGIC         FUND_ID
-- MAGIC         , FUND
-- MAGIC         , PORTFOLIO_ID
-- MAGIC         , PORTFOLIO
-- MAGIC         , REPORT_DATE
-- MAGIC         , SUM(COALESCE(CAPITAL_INJ,0)) CAPITAL_INJ
-- MAGIC         , SUM(COALESCE(DISPOSAL,0)) DISPOSAL
-- MAGIC     FROM TX
-- MAGIC     GROUP BY ALL
-- MAGIC     ORDER BY REPORT_DATE
-- MAGIC )
-- MAGIC , AUM_BRIDGE_BASE AS (
-- MAGIC     SELECT 
-- MAGIC     FUND_ID
-- MAGIC     , PORTFOLIO_ID
-- MAGIC     , REPORT_DATE
-- MAGIC     , COALESCE(CAPITAL_INJ, 0) AS CAPITAL_INJ
-- MAGIC     , ASSET_COMMITTED_EQUITY
-- MAGIC     , ASSET_EXTERNAL_DEBT
-- MAGIC     , COALESCE(DISPOSAL, 0) AS DISPOSAL
-- MAGIC     , FUND_LEVEL_ADJ
-- MAGIC     , CLOSING_AUM
-- MAGIC     FROM AUM
-- MAGIC     LEFT JOIN TRX USING (REPORT_DATE, FUND_ID, PORTFOLIO_ID)
-- MAGIC     ORDER BY REPORT_DATE
-- MAGIC )
-- MAGIC SELECT *
-- MAGIC FROM AUM_BRIDGE_BASE
-- MAGIC ''')
-- MAGIC
-- MAGIC AUM_BRIDGE_BASE.createOrReplaceTempView("AUM_BRIDGE_BASE")

-- COMMAND ----------

-- DBTITLE 1,PORTFOLIO_LEVEL
SELECT 
  FUND_ID
  , FUND
  , PORTFOLIO_ID
  , PORTFOLIO
  , REPORT_DATE
  , COALESCE(LAG(CLOSING_AUM) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0) AS OPENING_AUM
  , COALESCE(CAPITAL_INJ, 0) AS CAPITAL_INJ
  , CLOSING_AUM 
      - COALESCE(LAG(CLOSING_AUM) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0) 
      - COALESCE(CAPITAL_INJ, 0) 
      - (ASSET_COMMITTED_EQUITY - COALESCE(LAG(ASSET_COMMITTED_EQUITY) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0))
      - (ASSET_EXTERNAL_DEBT - COALESCE(LAG(ASSET_EXTERNAL_DEBT) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0))
      - COALESCE(DISPOSAL, 0) 
      - (FUND_LEVEL_ADJ - COALESCE(LAG(FUND_LEVEL_ADJ) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0))
      AS NAV_CHANGE
  , ASSET_COMMITTED_EQUITY - COALESCE(LAG(ASSET_COMMITTED_EQUITY) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0) AS ASSET_COMMITTED_EQUITY
  , ASSET_EXTERNAL_DEBT - COALESCE(LAG(ASSET_EXTERNAL_DEBT) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0) AS ASSET_EXTERNAL_DEBT
  , COALESCE(DISPOSAL, 0) AS DISPOSAL
  , FUND_LEVEL_ADJ - COALESCE(LAG(FUND_LEVEL_ADJ) OVER (PARTITION BY FUND_ID, PORTFOLIO_ID ORDER BY REPORT_DATE), 0) AS FUND_LEVEL_ADJ
  , CLOSING_AUM
FROM AUM_BRIDGE_BASE
JOIN (SELECT DISTINCT FUND_ID, FUND, PORTFOLIO_ID, PORTFOLIO FROM REGISTER) USING (FUND_ID, PORTFOLIO_ID)
WHERE AUM_BRIDGE_BASE.PORTFOLIO_ID != 'n/a_Undeployed' --NOT DISPLAYING UNDEPLOYED AS THEY ARE FUND LEVEL ADJUSTMENTS
ORDER BY REPORT_DATE, FUND, PORTFOLIO

-- COMMAND ----------

-- DBTITLE 1,FUND_LEVEL
SELECT 
  FUND_ID
  , FUND
  , REPORT_DATE
  , COALESCE(LAG(SUM(CLOSING_AUM)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0) AS OPENING_AUM
  , SUM(CAPITAL_INJ) AS CAPITAL_INJ
  , SUM(CLOSING_AUM) 
      - COALESCE(LAG(SUM(CLOSING_AUM)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0) 
      - SUM(CAPITAL_INJ) 
      - (SUM(ASSET_COMMITTED_EQUITY) - COALESCE(LAG(SUM(ASSET_COMMITTED_EQUITY)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0))
      - (SUM(ASSET_EXTERNAL_DEBT) - COALESCE(LAG(SUM(ASSET_EXTERNAL_DEBT)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0))
      - SUM(DISPOSAL) 
      - (SUM(FUND_LEVEL_ADJ) - COALESCE(LAG(SUM(FUND_LEVEL_ADJ)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0))
      AS NAV_CHANGE
  , SUM(ASSET_COMMITTED_EQUITY) - COALESCE(LAG(SUM(ASSET_COMMITTED_EQUITY)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0) AS ASSET_COMMITTED_EQUITY
  , SUM(ASSET_EXTERNAL_DEBT) - COALESCE(LAG(SUM(ASSET_EXTERNAL_DEBT)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0) AS ASSET_EXTERNAL_DEBT
  , SUM(DISPOSAL) AS DISPOSAL
  , SUM(FUND_LEVEL_ADJ) - COALESCE(LAG(SUM(FUND_LEVEL_ADJ)) OVER (PARTITION BY FUND_ID ORDER BY REPORT_DATE), 0) AS FUND_LEVEL_ADJ
  , SUM(CLOSING_AUM) AS CLOSING_AUM
FROM AUM_BRIDGE_BASE
JOIN (SELECT DISTINCT FUND_ID, FUND FROM REGISTER) USING (FUND_ID)
GROUP BY ALL
ORDER BY REPORT_DATE, FUND

-- COMMAND ----------

-- DBTITLE 1,OEGEN_LEVEL
SELECT 
  REPORT_DATE
  , COALESCE(LAG(SUM(CLOSING_AUM)) OVER (ORDER BY REPORT_DATE), 0) AS OPENING_AUM
  , SUM(CAPITAL_INJ) AS CAPITAL_INJ
  , SUM(CLOSING_AUM) 
      - COALESCE(LAG(SUM(CLOSING_AUM)) OVER (ORDER BY REPORT_DATE), 0) 
      - SUM(CAPITAL_INJ) 
      - (SUM(ASSET_COMMITTED_EQUITY) - COALESCE(LAG(SUM(ASSET_COMMITTED_EQUITY)) OVER (ORDER BY REPORT_DATE), 0))
      - (SUM(ASSET_EXTERNAL_DEBT) - COALESCE(LAG(SUM(ASSET_EXTERNAL_DEBT)) OVER (ORDER BY REPORT_DATE), 0))
      - SUM(DISPOSAL) 
      - (SUM(FUND_LEVEL_ADJ) - COALESCE(LAG(SUM(FUND_LEVEL_ADJ)) OVER (ORDER BY REPORT_DATE), 0))
      AS NAV_CHANGE
  , SUM(ASSET_COMMITTED_EQUITY) - COALESCE(LAG(SUM(ASSET_COMMITTED_EQUITY)) OVER (ORDER BY REPORT_DATE), 0) AS ASSET_COMMITTED_EQUITY
  , SUM(ASSET_EXTERNAL_DEBT) - COALESCE(LAG(SUM(ASSET_EXTERNAL_DEBT)) OVER (ORDER BY REPORT_DATE), 0) AS ASSET_EXTERNAL_DEBT
  , SUM(DISPOSAL) AS DISPOSAL
  , SUM(FUND_LEVEL_ADJ) - COALESCE(LAG(SUM(FUND_LEVEL_ADJ)) OVER (ORDER BY REPORT_DATE), 0) AS FUND_LEVEL_ADJ
  , SUM(CLOSING_AUM) AS CLOSING_AUM
FROM AUM_BRIDGE_BASE
GROUP BY ALL
ORDER BY REPORT_DATE