# Purpose
# Monthly AUM/NAV/GAV and related liquidity & commitment metrics at Portfolio × Fund × Report Date granularity, combining asset-level (from bronze_aum_asset) and fund-level (from bronze_aum_fund) inputs into a single, reconciled view. Where base values are missing, the table computes consistent substitutes from available components to avoid gaps and to enable downstream reporting.

silver_aum_metrics_enriched_sql_code = """
WITH
------------------------- GET AUM ASSET DATA -------------------------
  asset_data AS (
    SELECT
        REPORT_DATE,
        COMPANY_NAME,
        PORTFOLIO_NAME,
        FUND_SHORT,
        ASSET_NAV,
        NULL AS FUND_NAV,
        NULL AS FUM,
        PORTFOLIO_GAV,
        NULL AS FUND_GAV,
        AUM,
        ASSET_DRY_POWDER AS DRY_POWDER,
        NULL AS FUND_CASH_UP,
        NULL AS FUND_CASH_DOWN,
        NULL AS FUND_CASH_EXP,
        NULL AS FUND_CAPITAL_DR,
        NULL AS FUND_CASH_OTHER,
        NULL AS FUND_VALUE_ADJ,
        NULL AS FUND_REMOVE_DBL,
        NULL AS FUND_CONDITIONAL_ACQ_EQ,
        NULL AS TOTAL_FUND_DEBT,
        NULL AS UNDRAWN_FUND_DEBT,
        NULL AS TOTAL_COMMITTED,
        NULL AS EXPIRED_COMMITMENT,
        NULL AS TOTAL_CALLED,
        NULL AS RETURN_OF_CALL,
        NULL AS TOTAL_RECALLED,
        NULL AS TOTAL_FUND_CAPITAL_HR,
        EQ_VALUATION,
        LN_VALUATION,
        LOAN_BALANCE,
        ASSET_DEBT,
        ASSET_DEBT_CMT,
        ASSET_EQUITY_CMT,
        EXTERNAL_DEBT_COMMIT,
        ADJ_UNDRAWNCOMMITMENT,
        ASSET_LEVEL_CASH,
        ASSET_LEVEL_CASH_ADJ,
        datalake_ingestion_timestamp
    FROM {bronze_prefix}aum_asset aum_asset
    WHERE PORTFOLIO_NAME IS NOT NULL
      AND LOWER(PORTFOLIO_NAME) NOT LIKE '%null%'
)

------------------------- GET AUM FUND DATA -------------------------
, fund_data AS (
    SELECT 
        REPORT_DATE,
        Fund AS COMPANY_NAME,
        'Undeployed' AS PORTFOLIO_NAME,
        FUND_SHORT,
        NULL AS ASSET_NAV,
        FUND_NAV,
        FUM,
        NULL AS PORTFOLIO_GAV,
        FUND_GAV,
        FUND_AUM AS AUM,
        DRY_POWDER,
        FUND_CASH_UP,
        FUND_CASH_DOWN,
        FUND_CASH_EXP,
        FUND_CAPITAL_DR,
        FUND_CASH_OTHER,
        FUND_VALUE_ADJ,
        FUND_REMOVE_DBL,
        FUND_CONDITIONAL_ACQ_EQ,
        TOTAL_FUND_DEBT,
        UNDRAWN_FUND_DEBT,
        TOTAL_COMMITTED,
        EXPIRED_COMMITMENT,
        TOTAL_CALLED,
        RETURN_OF_CALL,
        TOTAL_RECALLED,
        TOTAL_FUND_CAPITAL_HR,
        NULL AS EQ_VALUATION,
        NULL AS LN_VALUATION,
        NULL AS LOAN_BALANCE,
        NULL AS ASSET_DEBT,
        NULL AS ASSET_DEBT_CMT,
        NULL AS ASSET_EQUITY_CMT,
        NULL AS EXTERNAL_DEBT_COMMIT,
        NULL AS ADJ_UNDRAWNCOMMITMENT,
        NULL AS ASSET_LEVEL_CASH,
        NULL AS ASSET_LEVEL_CASH_ADJ,
        aum_fund.datalake_ingestion_timestamp
    FROM {bronze_prefix}aum_fund aum_fund
    LEFT JOIN {bronze_prefix}fund fund
        ON aum_fund.FUND_SHORT = fund.Short_Name
)

------------------------- COMBINE ASSET & FUND AUM DATA -------------------------
, combined_data AS (
    SELECT * FROM asset_data
    UNION ALL
    SELECT * FROM fund_data
)

------------------------- AGGREGATE PORTFOLIO NUMERIC FIELDS FOR EACH REPORTING DATE  -------------------------
, grouped_combined_data AS (
  SELECT
    REPORT_DATE,
    PORTFOLIO_NAME,
    FUND_SHORT,

    -- Aggregate all numeric fields
    SUM(ASSET_NAV) AS ASSET_NAV,
    SUM(FUND_NAV) AS FUND_NAV,
    SUM(FUM) AS FUM,
    SUM(PORTFOLIO_GAV) AS PORTFOLIO_GAV,
    SUM(FUND_GAV) AS FUND_GAV,
    SUM(AUM) AS AUM,
    SUM(DRY_POWDER) AS DRY_POWDER,
    SUM(FUND_CASH_UP) AS FUND_CASH_UP,
    SUM(FUND_CASH_DOWN) AS FUND_CASH_DOWN,
    SUM(FUND_CASH_EXP) AS FUND_CASH_EXP,
    SUM(FUND_CAPITAL_DR) AS FUND_CAPITAL_DR,
    SUM(FUND_CASH_OTHER) AS FUND_CASH_OTHER,
    SUM(FUND_VALUE_ADJ) AS FUND_VALUE_ADJ,
    SUM(FUND_REMOVE_DBL) AS FUND_REMOVE_DBL,
    SUM(FUND_CONDITIONAL_ACQ_EQ) AS FUND_CONDITIONAL_ACQ_EQ,
    SUM(TOTAL_FUND_DEBT) AS TOTAL_FUND_DEBT,
    SUM(UNDRAWN_FUND_DEBT) AS UNDRAWN_FUND_DEBT,
    SUM(TOTAL_COMMITTED) AS TOTAL_COMMITTED,
    SUM(EXPIRED_COMMITMENT) AS EXPIRED_COMMITMENT,
    SUM(TOTAL_CALLED) AS TOTAL_CALLED,
    SUM(RETURN_OF_CALL) AS RETURN_OF_CALL,
    SUM(TOTAL_RECALLED) AS TOTAL_RECALLED,
    SUM(TOTAL_FUND_CAPITAL_HR) AS TOTAL_FUND_CAPITAL_HR,
    SUM(EQ_VALUATION) AS EQ_VALUATION,
    SUM(LN_VALUATION) AS LN_VALUATION,
    SUM(LOAN_BALANCE) AS LOAN_BALANCE,
    SUM(ASSET_DEBT) AS ASSET_DEBT,
    SUM(ASSET_DEBT_CMT) AS ASSET_DEBT_CMT,
    SUM(ASSET_EQUITY_CMT) AS ASSET_EQUITY_CMT,
    SUM(EXTERNAL_DEBT_COMMIT) AS EXTERNAL_DEBT_COMMIT,
    SUM(ADJ_UNDRAWNCOMMITMENT) AS ADJ_UNDRAWNCOMMITMENT,
    SUM(ASSET_LEVEL_CASH) AS ASSET_LEVEL_CASH,
    SUM(ASSET_LEVEL_CASH_ADJ) AS ASSET_LEVEL_CASH_ADJ,
    MAX(datalake_ingestion_timestamp) AS datalake_ingestion_timestamp
  FROM combined_data
  GROUP BY REPORT_DATE, PORTFOLIO_NAME, FUND_SHORT
)

------------------------- PERFORM CALCULATIONS  -------------------------
, derived_data AS (
    SELECT 
        *,

        CASE 
            WHEN ASSET_NAV IS NULL THEN 
                COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) 
            ELSE ASSET_NAV
        END AS CALC_ASSET_NAV,

        CASE 
            WHEN FUND_NAV IS NULL THEN 
                COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + 
                COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) - COALESCE(TOTAL_FUND_DEBT, 0) + 
                COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0)
            ELSE FUND_NAV
        END AS CALC_FUND_NAV,

        CASE 
            WHEN FUM IS NULL THEN 
                COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + 
                COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) - COALESCE(TOTAL_FUND_DEBT, 0) + 
                COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
                COALESCE(TOTAL_FUND_CAPITAL_HR, 0)
            ELSE FUM
        END AS CALC_FUM,

        CASE 
            WHEN PORTFOLIO_GAV IS NULL THEN 
                COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
                COALESCE(ASSET_DEBT, 0)
            ELSE PORTFOLIO_GAV
        END AS CALC_PORTFOLIO_GAV,

        CASE 
            WHEN FUND_GAV IS NULL THEN 
                COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
                COALESCE(ASSET_DEBT, 0) + COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + 
                COALESCE(FUND_CASH_EXP, 0) + COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0)
            ELSE FUND_GAV
        END AS CALC_FUND_GAV,

        CASE 
            WHEN AUM IS NULL THEN 
                COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
                COALESCE(ASSET_DEBT, 0) + COALESCE(ASSET_DEBT_CMT, 0) + COALESCE(ASSET_EQUITY_CMT, 0) + 
                COALESCE(EXTERNAL_DEBT_COMMIT, 0) + COALESCE(ADJ_UNDRAWNCOMMITMENT, 0) + 
                COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + 
                COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) + COALESCE(FUND_REMOVE_DBL, 0)
            ELSE AUM
        END AS CALC_AUM,

        CASE 
            WHEN DRY_POWDER IS NULL THEN 
                COALESCE(TOTAL_FUND_CAPITAL_HR, 0) + COALESCE(UNDRAWN_FUND_DEBT, 0) + COALESCE(FUND_CASH_OTHER, 0) + 
                COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + COALESCE(FUND_CAPITAL_DR, 0) + 
                COALESCE(ASSET_LEVEL_CASH, 0) + COALESCE(ASSET_LEVEL_CASH_ADJ, 0) - 
                COALESCE(ASSET_DEBT_CMT, 0) - COALESCE(ASSET_EQUITY_CMT, 0) - COALESCE(ADJ_UNDRAWNCOMMITMENT, 0) - 
                COALESCE(FUND_CONDITIONAL_ACQ_EQ, 0)
            ELSE DRY_POWDER
        END AS CALC_DRY_POWDER
    FROM grouped_combined_data
),

------------------------- PERFORM CHECKS - ALL SHOULD GIVE NULL OR ZERO  -------------------------
bulk_calcs AS (
    SELECT 
        PORTFOLIO_NAME,
        FUND_SHORT,
        REPORT_DATE,
        ASSET_NAV,
        FUND_NAV,
        FUM,
        PORTFOLIO_GAV,
        FUND_GAV,
        AUM,
        DRY_POWDER,

        FUND_CASH_UP, FUND_CASH_DOWN, FUND_CASH_EXP, FUND_CAPITAL_DR, FUND_CASH_OTHER,
        FUND_VALUE_ADJ, FUND_REMOVE_DBL, FUND_CONDITIONAL_ACQ_EQ, TOTAL_FUND_DEBT,
        UNDRAWN_FUND_DEBT, TOTAL_COMMITTED, EXPIRED_COMMITMENT, TOTAL_CALLED,
        RETURN_OF_CALL, TOTAL_RECALLED, TOTAL_FUND_CAPITAL_HR, EQ_VALUATION,
        LN_VALUATION, LOAN_BALANCE, ASSET_DEBT, ASSET_DEBT_CMT, ASSET_EQUITY_CMT,
        EXTERNAL_DEBT_COMMIT, ADJ_UNDRAWNCOMMITMENT, ASSET_LEVEL_CASH, ASSET_LEVEL_CASH_ADJ,

        CALC_ASSET_NAV,
        CALC_FUND_NAV,
        CALC_FUM,
        CALC_PORTFOLIO_GAV,
        CALC_FUND_GAV,
        CALC_AUM,
        CALC_DRY_POWDER,

        -- Final calculation checks
        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN COALESCE(EQ_VALUATION, 0) - COALESCE(ASSET_NAV, 0)
          ELSE COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) - COALESCE(ASSET_NAV, 0)
        END, 2) AS CHECK_ASSET_NAV,

        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN NULL
          ELSE
              COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + 
              COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) - COALESCE(TOTAL_FUND_DEBT, 0) + 
              COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) - COALESCE(CALC_FUND_NAV, 0)
        END, 2) AS CHECK_FUND_NAV,

        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN COALESCE(FUND_CASH_OTHER, 0) + COALESCE(EQ_VALUATION, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_VALUE_ADJ, 0) - COALESCE(TOTAL_FUND_DEBT, 0) - COALESCE(FUM, 0) - COALESCE(ASSET_NAV, 0)
          ELSE
              COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + 
              COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) - COALESCE(TOTAL_FUND_DEBT, 0) + 
              COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
              COALESCE(TOTAL_FUND_CAPITAL_HR, 0) - COALESCE(CALC_FUM, 0)
        END, 2) AS CHECK_FUM,

        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN NULL
          ELSE
            COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
            COALESCE(ASSET_DEBT, 0) - COALESCE(PORTFOLIO_GAV, 0)
        END, 2) AS CHECK_PORTFOLIO_GAV,

        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN NULL
          ELSE
            COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
            COALESCE(ASSET_DEBT, 0) + COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + 
            COALESCE(FUND_CASH_EXP, 0) + COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) - 
            COALESCE(CALC_FUND_GAV, 0)
        END, 2) AS CHECK_FUND_GAV,

        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN COALESCE(EQ_VALUATION, 0) + COALESCE(ASSET_DEBT, 0) + COALESCE(ASSET_EQUITY_CMT, 0) + COALESCE(ASSET_LEVEL_CASH, 0) + COALESCE(FUND_CASH_OTHER, 0) + COALESCE(TOTAL_FUND_CAPITAL_HR, 0) + COALESCE(FUND_CASH_DOWN, 0) - COALESCE(AUM, 0)
          ELSE
              COALESCE(EQ_VALUATION, 0) + COALESCE(LN_VALUATION, 0) + COALESCE(LOAN_BALANCE, 0) + 
              COALESCE(ASSET_DEBT, 0) + COALESCE(ASSET_DEBT_CMT, 0) + COALESCE(ASSET_EQUITY_CMT, 0) + 
              COALESCE(EXTERNAL_DEBT_COMMIT, 0) + COALESCE(ADJ_UNDRAWNCOMMITMENT, 0) + 
              COALESCE(FUND_CASH_UP, 0) + COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + 
              COALESCE(FUND_CASH_OTHER, 0) + COALESCE(FUND_VALUE_ADJ, 0) + COALESCE(FUND_REMOVE_DBL, 0) - COALESCE(CALC_AUM, 0)
        END, 2) AS CHECK_AUM,

        ROUND (
        CASE
          WHEN REPORT_DATE < DATE '2023-01-01' THEN NULL
          ELSE
            COALESCE(TOTAL_FUND_CAPITAL_HR, 0) + COALESCE(UNDRAWN_FUND_DEBT, 0) + COALESCE(FUND_CASH_OTHER, 0) + 
            COALESCE(FUND_CASH_DOWN, 0) + COALESCE(FUND_CASH_EXP, 0) + COALESCE(FUND_CAPITAL_DR, 0) + 
            COALESCE(ASSET_LEVEL_CASH, 0) + COALESCE(ASSET_LEVEL_CASH_ADJ, 0) - 
            COALESCE(ASSET_DEBT_CMT, 0) - COALESCE(ASSET_EQUITY_CMT, 0) - COALESCE(ADJ_UNDRAWNCOMMITMENT, 0) - 
            COALESCE(FUND_CONDITIONAL_ACQ_EQ, 0) - COALESCE(CALC_DRY_POWDER, 0)
        END, 2) AS CHECK_DRY_POWDER,

        datalake_ingestion_timestamp
        
    FROM derived_data
)

------------------------- GET ALL EFRONT AUM METRICS & CALCULATIONS, ADD IDs, AND EXCLUDE EMPTY VALUATIONS  -------------------------
, ef_aum_metrics_and_calculations AS (
  SELECT
      f.Fund_IQId,
      p.source_portfolio_id AS Portfolio_id,
      bulk_calcs.*
  FROM bulk_calcs

  LEFT JOIN {bronze_prefix}fund f
    ON f.Short_Name = bulk_calcs.FUND_SHORT
  LEFT JOIN oegen_data_prod_prod.core_data_model.bronze_mapping_portfolio p 
    ON p.source_portfolio_name = bulk_calcs.PORTFOLIO_NAME

  WHERE NOT (
  (
      ABS(
        COALESCE(ASSET_NAV, 0) +
        COALESCE(FUND_NAV, 0) +
        COALESCE(FUM, 0) +
        COALESCE(PORTFOLIO_GAV, 0) +
        COALESCE(FUND_GAV, 0) +
        COALESCE(AUM, 0) +
        COALESCE(DRY_POWDER, 0) +
        COALESCE(FUND_CASH_UP, 0) +
        COALESCE(FUND_CASH_DOWN, 0) +
        COALESCE(FUND_CASH_EXP, 0) +
        COALESCE(FUND_CAPITAL_DR, 0) +
        COALESCE(FUND_CASH_OTHER, 0) +
        COALESCE(FUND_VALUE_ADJ, 0) +
        COALESCE(FUND_REMOVE_DBL, 0) +
        COALESCE(FUND_CONDITIONAL_ACQ_EQ, 0) +
        COALESCE(TOTAL_FUND_DEBT, 0) +
        COALESCE(UNDRAWN_FUND_DEBT, 0) +
        COALESCE(TOTAL_COMMITTED, 0) +
        COALESCE(EXPIRED_COMMITMENT, 0) +
        COALESCE(TOTAL_CALLED, 0) +
        COALESCE(RETURN_OF_CALL, 0) +
        COALESCE(TOTAL_RECALLED, 0) +
        COALESCE(TOTAL_FUND_CAPITAL_HR, 0) +
        COALESCE(EQ_VALUATION, 0) +
        COALESCE(LN_VALUATION, 0) +
        COALESCE(LOAN_BALANCE, 0) +
        COALESCE(ASSET_DEBT, 0) +
        COALESCE(ASSET_DEBT_CMT, 0) +
        COALESCE(ASSET_EQUITY_CMT, 0) +
        COALESCE(EXTERNAL_DEBT_COMMIT, 0) +
        COALESCE(ADJ_UNDRAWNCOMMITMENT, 0) +
        COALESCE(ASSET_LEVEL_CASH, 0) +
        COALESCE(ASSET_LEVEL_CASH_ADJ, 0)
      ) < 0.005
    )
  AND PORTFOLIO_NAME != 'Undeployed'
  )
)

------------------------- GET EFRONT AUM METRICS & CALCULATIONS DATA (DERIVED ABOVE) -------------------------
, ef_aum_metrics as (
  select
    Fund_IQId AS ef_fund_id,
    Portfolio_id AS ef_portfolio_id,
    FUND_SHORT AS ef_fund,
    PORTFOLIO_NAME AS ef_portfolio,
    REPORT_DATE,
    FUND_CASH_UP,
    FUND_CASH_DOWN,
    FUND_CASH_EXP,
    FUND_CAPITAL_DR,
    FUND_CASH_OTHER,
    FUND_VALUE_ADJ,
    FUND_REMOVE_DBL,
    FUND_CONDITIONAL_ACQ_EQ,
    TOTAL_FUND_DEBT,
    UNDRAWN_FUND_DEBT,
    TOTAL_COMMITTED,
    EXPIRED_COMMITMENT,
    TOTAL_CALLED,
    RETURN_OF_CALL,
    TOTAL_RECALLED,
    TOTAL_FUND_CAPITAL_HR,
    EQ_VALUATION,
    LN_VALUATION,
    LOAN_BALANCE,
    ASSET_DEBT,
    ASSET_DEBT_CMT,
    ASSET_EQUITY_CMT,
    EXTERNAL_DEBT_COMMIT,
    ADJ_UNDRAWNCOMMITMENT,
    ASSET_LEVEL_CASH,
    ASSET_LEVEL_CASH_ADJ,
    CALC_ASSET_NAV AS ASSET_NAV,
    CALC_FUND_NAV AS FUND_NAV,
    CALC_FUM AS FUM,
    CALC_PORTFOLIO_GAV AS PORTFOLIO_GAV,
    CALC_FUND_GAV AS FUND_GAV,
    CALC_AUM AS AUM,
    CALC_DRY_POWDER AS DRY_POWDER,
    CHECK_ASSET_NAV,
    CHECK_FUND_NAV,
    CHECK_FUM,
    CHECK_PORTFOLIO_GAV,
    CHECK_FUND_GAV,
    CHECK_AUM,
    CHECK_DRY_POWDER,
    datalake_ingestion_timestamp
  from ef_aum_metrics_and_calculations
)

SELECT
  *,
  CURRENT_TIMESTAMP AS refresh_timestamp
FROM ef_aum_metrics
ORDER BY ef_portfolio, ef_fund, REPORT_DATE DESC
"""