table_config = {
    "aum_metrics": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_aum_metrics.py",
        "match_keys": ["ef_portfolio", "ef_fund", "REPORT_DATE"],
        "load_date_column": "refresh_timestamp",
    },
    "aum_metrics_enriched": {
        "level": 2,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_aum_metrics_enriched.py",
        "match_keys": ["ef_portfolio", "ef_fund", "REPORT_DATE"],
        "load_date_column": "refresh_timestamp",
    },
     "aum_capital_injections_and_disposals_transactions": {
        "level": 2,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_aum_capital_injections_and_disposals_transactions.py",
        "match_keys": ["transaction_id"],
        "load_date_column": "refresh_timestamp",
    },
    "aggregated_asset_transactions": {
        "level": 2,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_aggregated_asset_transactions.py",
        "match_keys": ["company", "company_investor", "instrument", "type", "report_date"],
        "load_date_column": "refresh_timestamp",
    },
    "company": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_company.py",
        "match_keys": ["Company_IQId"],
        "load_date_column": "refresh_timestamp",
    },
    "fund": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fund.py",
        "match_keys": ["ef_fund_id"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_raw": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_raw.py",
        "match_keys": ["ef_fund_id", "investor_account", "fund_currency", "effective_date", "amount_fund_curr", "modified_on", "type"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_daily": {
        "level": 2,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_daily.py",
        "match_keys": ["Ef_Fund_Id", "Investor", "Transaction_Currency", "Investor_Type", "Investor_Country", "Effective_Date"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_monthly": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_monthly_calendarised.py",
        "match_keys": ["Ef_Fund_Id", "Investor", "Transaction_Currency", "Year_Month"],
        "load_date_column": "refresh_timestamp"
    },
    "fundoperations_quarterly": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_quarterly_calendarised.py",
        "match_keys": ["Ef_Fund_Id", "Investor", "Transaction_Currency", "Year_Quarter"],
        "load_date_column": "refresh_timestamp"
    },
    "fundoperations_by_investor": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_by_investor.py",
        "match_keys": ["Investor", "Transaction_Currency", "Investor_Type", "Investor_Country", "Effective_Date"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_by_investor_type_monthly": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_by_investor_type_monthly_calendarised.py",
        "match_keys": ["Fund", "Investor_Type", "Year_Month"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_by_investor_country_monthly": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_by_investor_country_monthly_calendarised.py",
        "match_keys": ["Fund", "Investor_Country", "Year_Month"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_by_investor_type_quarterly": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_by_investor_type_quarterly_calendarised.py",
        "match_keys": ["Fund", "Investor_Type", "Year_Quarter"],
        "load_date_column": "refresh_timestamp",
    },
    "fundoperations_by_investor_country_quarterly": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fundoperations_by_investor_country_quarterly_calendarised.py",
        "match_keys": ["Fund", "Investor_Country", "Year_Quarter"],
        "load_date_column": "refresh_timestamp",
    },
    "fees_company": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fees_company.py",
        "match_keys": ["IQId"],
        "load_date_column": "refresh_timestamp",
    },
    "fees_fund": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fees_fund.py",
        "match_keys": ["IQId", "Investor_Account_IQId"],
        "load_date_column": "refresh_timestamp",
    },
    "instruments": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_instruments.py",
        "match_keys": ["Company_IQId", "Instrument", "Portfolio", "Description", "Currency"],
        "load_date_column": "refresh_timestamp",
    },
    "investment_portfolio_track_record_reporting": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_investment_portfolio_track_record_reporting.py",
        "match_keys": ["investment_portfolio_id"],
        "load_date_column": "refresh_timestamp",
    },
    "investor": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_investor.py",
        "match_keys": ["Investor_IQId"],
        "load_date_column": "refresh_timestamp",
    },
    "ownership": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_ownership.py",
        "match_keys": ["Company_IQId", "Fund_IQId", "Company_Investor_IQId"],
        "load_date_column": "refresh_timestamp",
    },
    "datapointsexport": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_datapointsexport.py",
        "match_keys": ["CATEGORY_NAME", "DATAPOINT_NAME", "ENTITY", "ENTITY_NAME", "REPORTINGDATE"],
        "load_date_column": "refresh_timestamp",
    },
    "track_record_fund_raw": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_track_record_fund_raw.py",
        "match_keys": ["FUND_SHORT"],
        "load_date_column": "refresh_timestamp",
    },
    "fx_vs_gbp": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_fx_vs_gbp.py",
        "match_keys": ["currency", "ref_date"],
        "load_date_column": "refresh_timestamp",
        "uniqueness_expectations": {
            "composite": [["currency", "ref_date"]]
        }
    },
    "investoraccount": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_investoraccount.py",
        "match_keys": ["investor_account_id", "investor_id", "ef_fund_id"],
        "load_date_column": "refresh_timestamp",
    },
    "track_record_fund": {
        "level": 3,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_track_record_fund.py",
        "match_keys": ["ef_fund", "metric"],
        "load_date_column": "refresh_timestamp",
        "uniqueness_expectations": {
            "composite": [["ef_fund", "metric"]]
        }
    },
    "track_record_metric_dictionary": {
        "level": 2,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_track_record_metric_dictionary.py",
        "match_keys": ["domain", "source_system_id", "dataset_name", "metric"],
        "load_date_column": "refresh_timestamp",
        "uniqueness_expectations": {
            "composite": [["domain", "source_system_id", "dataset_name", "metric"]]
        }
    },
    "transactions": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_transactions.py",
        "match_keys": ["transaction_id"],
        "load_date_column": "refresh_timestamp",
    },
    "transactions_paid": {
        "level": 1,
        "code_type": "sql",
        "table_type": "overwrite_in_place",
        "file_name": "silver_transactions_paid.py",
        "match_keys": ["transaction_id", "date_paid"],
        "load_date_column": "refresh_timestamp",
    },
}
