silver_track_record_metric_dictionary_sql_code = r"""
WITH datapoints_metrics AS (
    SELECT
        'fund' AS domain,
        'SRCE_SYST_1001' AS source_system_id,
        'datapointsexport' AS dataset_name,
        regexp_replace(
            lower(regexp_replace(DATAPOINT_NAME, '[\\s\\(\\)]+', '_')),
            '_$', ''
        ) AS metric
    FROM (
        SELECT DISTINCT DATAPOINT_NAME
        FROM {silver_prefix}datapointsexport
        WHERE lower(CATEGORY_NAME) = 'fund metrics'
          AND lower(ENTITY_TYPE) = 'fund'
    )
),
tr_metrics AS (
    SELECT
        'fund' AS domain,
        'SRCE_SYST_1001' AS source_system_id,
        'track_record_fund' AS dataset_name,
        metric
    FROM VALUES
        ('annualised_yield'),
        ('annual_yield'),
        ('dpi'),
        ('moic'),
        ('net_cagr'),
        ('net_total_return'),
        ('unrealised_gross_irr'),
        ('unrealised_net_irr'),
        ('weighted_yield_units'),
        ('annual_net_irr'),
        ('nav_yield'),
        ('quarterly_yield')
    AS t(metric)
),
metric_display_names AS (
    SELECT metric AS normalised_metric, display_name
    FROM oegen_data_prod_prod.core_data_model.ref_metric_display_name_mapping
),
metric_definitions AS (
    SELECT * FROM VALUES
        ('annual_net_irr', 'The Internal Rate of Return calculated over a specific 1-year trailing period (or annualised over the life of the fund), net of management fees, expenses, and carried interest.'),
        ('annual_yield', 'The total income (dividends/interest) actually generated and paid out by the investment over a trailing 12-month period, expressed as a percentage of the fund''s NAV or invested capital.'),
        ('annualised_yield', 'Total cash distributions to investors divided by the value of drawdowns since inception converted into an annual rate.'),
        ('net_cagr', 'Compound Annual Growth Rate. The smoothed, annualised rate of return of an investment over a specified period longer than one year, net of fees.'),
        ('dpi', 'Distributions to Paid-In Capital - Ratio of total distributions over contributed capital since inception.'),
        ('dividend_cover_ratio', 'Undefined...'),
        ('annualised_dividend_paid', 'A forward-looking run-rate extrapolating a specific dividend amount for a quarter or month to estimate the full 12-month period payout.'),
        ('moic', 'Multiple on Invested Capital - Ratio of the total value (realised plus unrealised) to the total invested capital.'),
        ('nav_yield', 'The total income distributions divided by the fund''s current Net Asset Value.'),
        ('quarterly_yield', 'The income generated by the fund over a single quarter, expressed as a percentage of NAV or invested capital.'),
        ('target_net_irr', 'The desired or expected Internal Rate of Return for a fund or investment, net of fees.'),
        ('total_nav_return', 'The cumulative (non-annualised) return based on the growth of the Net Asset Value plus any distributions, from inception to date.'),
        ('total_nav_return_annualised', 'Annualised growth using the Net Asset Value, accounting for distributions.'),
        ('net_total_return', 'The investor''s cumulative economic return from the beginning of the fund through capital growth and reinvested income.'),
        ('total_shareholder_return', 'The cumulative (non-annualised) return experienced by an investor, reflecting changes in the publicly traded share price plus any dividends received.'),
        ('total_shareholder_return_annualised', 'Annualised rate of return reflecting changes in share price plus dividends.'),
        ('unrealised_gross_irr', 'The Internal Rate of Return calculated strictly on the active, unsold portion of the portfolio, before deducting fund-level fees and carry.'),
        ('unrealised_net_irr', 'The Internal Rate of Return on the active, unsold portfolio, calculated after deducting estimated fund-level fees and accrued carried interest.'),
        ('weighted_average_discount_rate', 'The average discount rate used in Discounted Cash Flow (DCF) models to value the fund''s unlisted assets, weighted by proportional value.'),
        ('weighted_yield_units', 'The overall yield of a portfolio calculated by taking the individual yield of each underlying asset and weighting it by its proportional sise.')
    AS t(normalised_metric_def, definition)
),
all_metrics AS (
    SELECT * FROM datapoints_metrics
    UNION ALL
    SELECT * FROM tr_metrics
)
SELECT
    m.domain,
    m.source_system_id,
    m.dataset_name,
    m.metric AS normalised_metric,
    d.display_name AS metric,
    def.definition,
    current_timestamp() AS refresh_timestamp
FROM all_metrics m
LEFT JOIN metric_display_names d ON m.metric = d.normalised_metric
LEFT JOIN metric_definitions def ON m.metric = def.normalised_metric_def
ORDER BY d.display_name
"""
