table_name: bronze_asset_lifecycle_milestones_dim_core

roles:
  primary_keys: [lifecycle_milestone_id, START_AT]
  system_keys: [lifecycle_milestone_id, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT

checks:
  # table-specific checks (in addition to defaults)

  - template: is_not_null
    name: required_fields_is_not_null_hard_check
    criticality: error
    params:
      columns:
        - lifecycle_milestone_name
        - lifecycle_milestone_definition
        - lifecycle_phase_id
        
        

  - template: fk_exists
    name: lifecycle_phase_id_fk_exists
    criticality: error
    params:
      fk_columns: [lifecycle_phase_id]
      ref_table: bronze_asset_lifecycle_phases_dim_core
      ref_columns: [current_lifecycle_phase_id]



  - template: string_pattern_match
    name: lifecycle_milestone_id_string_pattern
    criticality: error
    params:
      columns: lifecycle_milestone_id
      pattern: "^LIFE_MILE_\\d{4}$"  # Double backslash for YAML escaping