table_name: bronze_investment_portfolio_dim_core_af

roles:
  primary_keys: [investment_portfolio_id, START_AT]
  system_keys: [investment_portfolio_id, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT

checks:
  # table-specific checks (in addition to defaults)

  - template: is_not_null
    name: required_fields_is_not_null
    criticality: error
    params:
      columns:
        - investment_portfolio_name 
        - invp_fund_core_id
        - inv_pipeline_type
        - invp_investment_strategy

  - template: fk_exists
    name: invp_fund_core_id_fk_exists
    criticality: error
    params:
      fk_columns: [invp_fund_core_id]
      ref_table: bronze_fund_dim_core
      ref_columns: [fund_core_id]

  - template: string_pattern_match
    name: investment_portfolio_id_string_pattern
    criticality: error
    params:
      columns: investment_portfolio_id
      pattern: "^INVP_\\d{4}$"  # Double backslash for YAML escaping