table_name: bronze_company_dim_lifecycle

roles:
  primary_keys: [company_lifecycle_id, START_AT]
  system_keys: [company_lifecycle_id, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT

checks:
  # table-specific checks (in addition to defaults)

  - template: is_not_null
    name: required_fields_is_not_null_hard_check
    criticality: error
    params:
      columns:
        - company_lifecycle_name
        - company_lifecycle_description




  - template: string_pattern_match
    name: company_lifecycle_id_string_pattern
    criticality: error
    params:
      columns: company_lifecycle_id
      pattern: "^COMP_LCYC_DEF_\\d{4}$"  # Double backslash for YAML escaping