table_name: bronze_investment_portfolio_bridge

roles:
  primary_keys: [invp_bridge_id]
  system_keys: [investment_portfolio_id, invp_version_id, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT

checks:
  - template: fk_exists
    name: invp_fk_exists
    criticality: error
    params:
      fk_columns: [investment_portfolio_id]
      ref_table: bronze_investment_portfolio_dim_core_af
      ref_columns: [investment_portfolio_id]

  - template: fk_exists
    name: invp_version_fk_exists
    criticality: error
    params:
      fk_columns: [invp_version_id]
      ref_table: bronze_investment_portfolio_fact_version
      ref_columns: [invp_version_id]


  - template: string_pattern_match
    name: invp_bridge_id_string_pattern
    criticality: error
    params:
      columns: invp_bridge_id
      pattern: "^INVP_BRDG_\\d{4}$"  # Double backslash for YAML escaping