table_name: bronze_fund_dim_attributes

roles:
  primary_keys: [fund_attribute_id, START_AT]
  system_keys: [fund_attribute_id, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT

checks:
  # table-specific checks (in addition to defaults)

  - template: is_not_null
    name: required_fields_is_not_null_hard_check
    criticality: error
    params:
      columns:
        - fund_attribute_definition
        - fund_attribute_def_description



  - template: string_pattern_match
    name: fund_attribute_id_string_pattern
    criticality: error
    params:
      columns: fund_attribute_id
      pattern: "^FUND_ATTR_\\d{4}$"  # Double backslash for YAML escaping