table_name: bronze_mapping_asset

roles:
  primary_keys: [source_system_id, source_asset_name, source_asset_id, cdm_asset_id]

checks:
  # table-specific checks (in addition to defaults)

  - template: fk_exists
    name: asset_id_fk_exists
    criticality: error
    params:
      fk_columns: ["cdm_asset_id"]     # Column in current table
      ref_columns: ["asset_id"]        # What we want to call it for the join
      ref_table: 
        - bronze_asset_infra_dim_core
        - bronze_asset_platform_dim_core
      source_ref_columns:              # The actual names in those specific tables
        - ["asset_infra_id"]           # Maps to 1st table
        - ["asset_plat_id"]            # Maps to 2nd table

  - template: fk_exists
    name: source_system_id_fk_exists
    criticality: error
    params:
      fk_columns: [source_system_id]
      ref_table: bronze_mapping_system_sources
      ref_columns: [source_system_id]