defaults:
  checks:
    - template: is_not_null
      name: system_keys_not_null
      criticality: error
      when_roles_present: [system_keys]
      params:
        columns_from_role: system_keys
    
    - template: is_not_null
      name: primary_keys_not_null
      criticality: error
      when_roles_present: [primary_keys]
      params:
        columns_from_role: primary_keys

    - template: is_not_null
      name: business_keys_not_null
      criticality: error
      when_roles_present: [business_keys]
      params:
        columns_from_role: business_keys



    - template: pk_unique
      name: primary_keys_unique
      criticality: error
      when_roles_present: [primary_keys]
      params:
        columns_from_role: primary_keys



    - template: no_future_timestamps
      name: system_start_at_not_future
      criticality: warn
      when_roles_present: [system_start_at]
      params:
        columns_from_role: system_start_at
        merge_columns_from_role: primary_keys

    - template: no_future_timestamps
      name: system_end_at_not_future
      criticality: warn
      when_roles_present: [system_end_at]
      params:
        columns_from_role: system_end_at
        merge_columns_from_role: primary_keys



    - template: is_in_range
      name: system_start_at_reasonable
      criticality: warn
      when_roles_present: [system_start_at]
      params:
        columns_from_role: system_start_at
        min_limit: "1990-01-01"
        max_limit: "2100-01-01"

    - template: is_in_range
      name: system_end_at_reasonable
      criticality: warn
      when_roles_present: [system_end_at]
      params:
        columns_from_role: system_end_at
        min_limit: "1990-01-01"
        max_limit: "2100-01-01"



    # SYSTEM ACTIVE PERIODS
    # system-active SCD2 checks
    - template: is_not_null
      name: system_start_at_not_null
      criticality: error
      when_roles_present: [system_start_at]
      params:
        columns_from_role: system_start_at

    - template: scd2_pk_unique
      name: scd2_pk_unique_system_keys
      criticality: error
      when_roles_present: [system_keys, system_start_at]
      params:
        start_col_from_role: system_start_at

    - template: scd2_no_overlap
      name: scd2_no_overlap_system_keys
      criticality: error
      when_roles_present: [system_keys, system_start_at, system_end_at]
      params:
        start_col_from_role: system_start_at
        end_col_from_role: system_end_at
        merge_columns_from_role: primary_keys

    - template: scd2_contiguous
      name: scd2_contiguous_system_keys
      criticality: error
      when_roles_present: [system_keys, system_start_at, system_end_at]
      params:
        start_col_from_role: system_start_at
        end_col_from_role: system_end_at
        merge_columns_from_role: primary_keys
    
    - template: scd2_start_after_end
      name: scd2_start_after_end_system_keys
      criticality: error
      when_roles_present: [system_keys, system_start_at, system_end_at]
      params:
        start_col_from_role: system_start_at
        end_col_from_role: system_end_at
        merge_columns_from_role: primary_keys
    
    - template: scd2_zero_length_interval
      name: scd2_zero_length_interval_system_keys
      criticality: error
      when_roles_present: [system_keys, system_start_at, system_end_at]
      params:
        start_col_from_role: system_start_at
        end_col_from_role: system_end_at
        merge_columns_from_role: primary_keys



    # BUSINESS ACTIVE PERIODS
    # business-active SCD2 checks (only when present)
    # not checking for future timestamps for business periods because we have these and they are needed (e.g. baseline/forecast milestones)
    - template: is_not_null
      name: business_start_at_not_null
      criticality: error
      when_roles_present: [business_start_at]
      params:
        columns_from_role: business_start_at

    - template: scd2_pk_unique
      name: scd2_pk_unique_business_keys
      criticality: error
      when_roles_present: [business_keys, business_start_at]
      params:
        start_col_from_role: business_start_at

    - template: scd2_no_overlap
      name: scd2_no_overlap_business_keys
      criticality: error
      when_roles_present: [business_keys, business_start_at, business_end_at]
      params:
        start_col_from_role: business_start_at
        end_col_from_role: business_end_at
        merge_columns_from_role: primary_keys

    - template: scd2_contiguous
      name: scd2_contiguous_business_keys
      criticality: error
      when_roles_present: [business_keys, business_start_at, business_end_at]
      params:
        start_col_from_role: business_start_at
        end_col_from_role: business_end_at
        merge_columns_from_role: primary_keys

    - template: scd2_start_after_end
      name: scd2_start_after_end_business_keys
      criticality: error
      when_roles_present: [business_keys, business_start_at, business_end_at]
      params:
        start_col_from_role: business_start_at
        end_col_from_role: business_end_at
        merge_columns_from_role: primary_keys
    
    - template: scd2_zero_length_interval
      name: scd2_zero_length_interval_business_keys
      criticality: error
      when_roles_present: [business_keys, business_start_at, business_end_at]
      params:
        start_col_from_role: business_start_at
        end_col_from_role: business_end_at
        merge_columns_from_role: primary_keys