table_name: bronze_asset_ownership_milestones_dim_core

roles:
  primary_keys: [ownership_milestone_id, START_AT]
  system_keys: [ownership_milestone_id, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT

checks:
  # table-specific checks (in addition to defaults)

  - template: is_not_null
    name: required_fields_is_not_null_hard_check
    criticality: error
    params:
      columns:
        - ownership_milestone_name
        - ownership_milestone_order
        - ownership_milestone_definition
        - ownership_phase_id
        

  - template: fk_exists
    name: ownership_phase_id_fk_exists
    criticality: error
    params:
      fk_columns: [ownership_phase_id]
      ref_table: bronze_asset_ownership_phases_dim_core
      ref_columns: [ownership_phase_id]


  - template: string_pattern_match
    name: ownership_milestone_id_string_pattern
    criticality: error
    params:
      columns: ownership_milestone_id
      pattern: "^OWNR_MILE_\\d{4}$"  # Double backslash for YAML escaping