table_name: bronze_asset_lifecycle_milestones_fact

roles:
  primary_keys: [asset_id, lifecycle_milestone_id, milestone_type_id, lifecycle_milestone_date, START_AT]
  system_keys: [asset_id, lifecycle_milestone_id, milestone_type_id, lifecycle_milestone_date, START_AT]
  system_start_at: START_AT
  system_end_at: END_AT


checks:
  # table-specific checks (in addition to defaults)

  - template: fk_exists
    name: asset_infra_id_fk_exists
    criticality: error
    params:
      fk_columns: [asset_id]
      ref_table: bronze_asset_infra_dim_core
      ref_columns: [asset_infra_id]

  - template: fk_exists
    name: lifecycle_milestone_id_fk_exists
    criticality: error
    params:
      fk_columns: [lifecycle_milestone_id]
      ref_table: bronze_asset_lifecycle_milestones_dim_core
      ref_columns: [lifecycle_milestone_id]

  
  - template: fk_exists
    name: milestone_type_id_fk_exists
    criticality: error
    params:
      fk_columns: [milestone_type_id]
      ref_table: bronze_asset_milestone_types_dim_core
      ref_columns: [milestone_type_id]